### ISSUE TITLE
default duration 

### ISSUE THREAD

**Issue by alexmitrani** [climu/OSR-discord-bot#18]
I am finding I tend to forget to type !no go when I am no longer looking for a game, and I think this happens to other people too.  I propose (1) setting a shorter default duration for the LFG role, say 60 minutes.   At the moment the default duration is infinite.  That way, longer durations will need to be explicitly requested, which will make it easier for people to remember that they will need cancelling.  (2) reminding people at the outset to type !no go when they are no longer looking for a game.  (3) checking back at intervals with people who specify long LFG durations - are you really still looking for a game?  The core idea is to reduce the occurrence of false positives - cases where the bot says someone is LFG when they aren't really.

**Comment by d-korni** [comment]
This is a good ground for developing further the bot.
Some points to make:
- Current "infinite" duration is due to a bug
- Alternative current duration is one day, but perhaps as you say, maybe we should reduce this to an hour or two (your point #1)
- If the player is not online in Discord, then they should not be listed

Point #2, you mean to display a message when they type `!go` that they should type `!no go` when they are no longer interested in playing?

Point #3, how do you imagine this? Perhaps a DM message to the user asking if they are still up for playing?

**Comment by alexmitrani** [comment]
on point 2 - yes
on point 3 - DM would be ideal, if possible
Also, there should probably be a maximum time someone can ask the bot to keep them looking for a game - maybe 12 hours?

**Comment by d-korni** [comment]
Sounds good. This is all possible, as long as we manage to fix the bug in a sensible manner.

**Comment by climu** [comment]
I think we should clarify what it means to be in `player` role.  It have been discussed in discord and I think it means one is ok being tag for games. It doesn't imply the user is activly looking for a game.

This is because many players are not actively looking for a game but might take the chance to play from time to time.

Then the duration is less a worry. It doesn't mean we won't implement it. It's just a less urgent feature I believe.

**Comment by d-korni** [comment]
Is this really the view people have for `player` role? I remember one person (can't remember who at the moment) that said they want to be in this role even if they are not actively looking, but I think the majority of the use would be for those actively and currently looking. At least, so far this has been the set-up and the use.

It sounds to me as if, we will need a command to accomodate the occasional player who wants to stay for infinite time. So a comand like `!go inf` to fix the `player` role maybe?

**Comment by climu** [comment]
hum...

I fear that lately it have been harder to find game due to this use of the bot.

We use to tag everyone for games request and it was working quite fine. Only issue was that some few people were annoyed to be taged all the time. The way I sees it is those annoyed people would not have the `player` role.

Basically, we keep the same, working, flow, but with people being able to get out of it if they want.
It has been discussed in discord and I thought we agreed on that. People activly looking for a game can always join the voice I want to play channel and tag `player` as they use to tag `here`. Same as before.

People not using it this way is because the bot was not announced nor documented yet and the "looking for a game" was inducing the opposite.

I fear otherwise we will loose people taking chance to play a game while they were not actively looking. those could have been a big part of OSR games.

**Comment by d-korni** [comment]
This functionality has now been removed.
